name=BananaKit2
version=2.0.0
author=Siqi Yan
maintainer=Siqi Yan <yansq2012@gmail.com>
sentence=The firmware repository for BananaKit2
paragraph=BananaKit2 is a custom designed MCU development platform based on Arduino Nano
category=Sensors
url=https://github.com/siqiyan/BananaKit2
architectures=*
